### PR TITLE
delta delta function

### PR DESCRIPTION
**Pull request by FellowFish**
Added delta delta for mean difference. deltadelta parameter takes in boolean TRUE or FALSE
Data:
set.seed(54321)

N = 30
c1 <- rnorm(N, mean = 100, sd = 25)
c2 <- rnorm(N, mean = 100, sd = 50)
g1 <- rnorm(N, mean = 120, sd = 25)
g2 <- rnorm(N, mean = 80, sd = 50)
g3 <- rnorm(N, mean = 100, sd = 12)
g4 <- rnorm(N, mean = 100, sd = 50)
gender <- c(rep('Male', N/2), rep('Female', N/2))
dummy <- rep("Dummy", N)
id <- 1: N

wide.data <- 
  tibble::tibble(
    Control1 = c1, Control2 = c2,
    Group1 = g1, Group2 = g2, Group3 = g3, Group4 = g4,
    Dummy = dummy,
    Gender = gender, ID = id)

my.data   <- 
  wide.data %>%
  tidyr::gather(key = Group, value = Measurement, -ID, -Gender, -Dummy)

Mean Difference: 
dd.data <- 
  my.data %>%
  dabest(Group, Measurement, 
         idx = list(c("Control1", "Control2"), 
                    c("Group1", "Group3")),
         paired = "sequential" , id.col = ID, deltadelta = TRUE
  )
dd.data.mean <- mean_diff(dd.data)
dd.data.mean

image

Graph: 
plot(dd.data.mean, 
     color.column = Gender)
image

### CODE REVIEW

**Comment by FellowFish** [comment]
Added changes to bca ci calculations. 

Following the same data as above we have

Mean Difference:
image

Graph:
image

**Comment by FellowFish** [comment]
I have adjusted the side of the delta delta plot so that it now takes up the entire graph

Code: 
`set.seed(54321)

N = 30
c1 <- rnorm(N, mean = 100, sd = 25)
c2 <- rnorm(N, mean = 100, sd = 50)
g1 <- rnorm(N, mean = 120, sd = 25)
g2 <- rnorm(N, mean = 80, sd = 50)
g3 <- rnorm(N, mean = 100, sd = 12)
g4 <- rnorm(N, mean = 100, sd = 50)
gender <- c(rep('Male', N/2), rep('Female', N/2))
dummy <- rep("Dummy", N)
id <- 1: N

wide.data <- 
  tibble::tibble(
    Control1 = c1, Control2 = c2,
    Group1 = g1, Group2 = g2, Group3 = g3, Group4 = g4,
    Dummy = dummy,
    Gender = gender, ID = id)


my.data   <- 
  wide.data %>%
  tidyr::gather(key = Group, value = Measurement, -ID, -Gender, -Dummy)

dd.data <- 
  my.data %>%
  dabest(Group, Measurement, 
         idx = list(c("Control1", "Control2"), 
                    c("Group1", "Group3")),
         paired = "sequential" , id.col = ID, deltadelta = TRUE
  )
dd.data.mean <- mean_diff(dd.data)

plot(dd.data.mean, 
     color.column = Gender)
`

Graph:
image


Also added new option called deltadelta.name that allows changing of the labels in deltadelta, but unsure if it is useful. 

Code:
`dd.data2 <- 
  my.data %>%
  dabest(Group, Measurement, 
         idx = list(c("Control1", "Control2"), 
                    c("Group1", "Group3")),
         paired = FALSE , deltadelta = TRUE,
         deltadelta.name = c("Ctrl", "Grp")
  )
dd.data.mean2 <- mean_diff(dd.data2)

plot(dd.data.mean2, 
     color.column = Gender)`

Graph:
image

**Comment by adamcc** [comment]
Great, I think that is fine. It seems that while DABEST-py makes the different curves the same width, that dabestr normalizes the curves by total area. So i wonder if leaving it the way it was is more consistent for this package.

**Comment by FellowFish** [comment]
The parameter name has been changed to delta2 to match the deltadelta function on the python side. 

Preparing the data:
`set.seed(54321)

N = 30
c1 <- rnorm(N, mean = 100, sd = 25)
c2 <- rnorm(N, mean = 100, sd = 50)
g1 <- rnorm(N, mean = 120, sd = 25)
g2 <- rnorm(N, mean = 80, sd = 50)
colour <- c(rep('Red', N/2), rep('Blue', N/2))
dummy <- rep("Dummy", N)
id <- 1: N

wide.data <- 
  tibble::tibble(
    Control1 = c1, Control2 = c2,
    Test1 = g1, Test2 = g2,
    Dummy = dummy,
    Colour = colour, ID = id)


my.data   <- 
  wide.data %>%
  tidyr::gather(key = Group, value = Measurement, -ID, -Colour, -Dummy)

my.data[my.data$Group == "Test1","Colour"] <- "Green"
my.data[my.data$Group == "Test2","Colour"] <- "Green"


tdd.paired <- 
  my.data %>%
  dabest(Group, Measurement, 
         idx = list(c("Control1", "Control2"),
                    c("Test1", "Test2")), 
         paired = TRUE, id.col = ID, delta2 = TRUE)`

Numerical:
`tdd.paired %>% 
  mean_diff()`

image


Graph:
`tdd.paired %>% 
  mean_diff() %>% 
  plot(color.column = Colour)`

image

**Pull request merged**
